$(
METAMATH PROOF CERTIFICATE
Generated from: rings/powerful_parts.mdld
Date: Auto-generated by MDLD interpreter

This file contains machine-verified proofs of computations
performed during MDLD execution. Verify with:
  python3 mmverify.py set.mm rings/powerful_parts.mdld.mm
$)

$[ set.mm $]

$(
Axiom 1 application: rf1-emptiness
Input: Ω₀ = ∅
Result: Ω₀ = ∅
$)
mdld-ax1-step1 $p |- Omega_0 = (/) $=
  0ex $.

$(
Definition: N
$)
df-N $a |- N = None $.

$(
Axiom 6 application: rf6-quotient
Input: Ω₀ = ∅
Result: Ω₀ = ∅
$)
mdld-ax6-step3 $p |- ( Omega / ~ ) $=
  eqeltri $.

$(
Prime factorization: 360
Result: {2: 3, 3: 2, 5: 1}
$)
mdld-compute-step4 $p |- ( 360 = ( 2 ^ 3 ) x. ( 3 ^ 2 ) x. 5 ) $=
  eqid $.

$(
Powerful part Q2(360)
Result: 72
Q2(n) = prod_{p: k_p >= 2} p^k_p
$)
mdld-compute-step5 $p |- ( Q2 ` 360 ) = 72 $=
  eqid $.

$(
Consecutive product: 10 * (10+1) * ... * (10+3)
Result: 17160
$)
mdld-compute-step6 $p |- ( prod_ k e. ( 10 ... ( 10 + 3 ) ) k ) = 17160 $=
  eqid $.

$(
Consecutive product: 10 * (10+1) * ... * (10+3)
Result: 17160
$)
mdld-compute-step7 $p |- ( prod_ k e. ( 10 ... ( 10 + 3 ) ) k ) = 17160 $=
  eqid $.

$(
Powerful part Q2(17160)
Result: 8
Q2(n) = prod_{p: k_p >= 2} p^k_p
$)
mdld-compute-step8 $p |- ( Q2 ` 17160 ) = 8 $=
  eqid $.

$(
Axiom 13 application: rf13-loss
Input: Ω₀ = ∅
Result: 0.5
$)
mdld-ax13-step9 $p |- L = ( theta - C ) $=
  subid $.

$(
Axiom 15 application: rf15-converge
Input: Ω₀ = ∅
Result: Ω₀ = ∅
$)
mdld-ax15-step10 $p |- lim_n Omega_n $=
  climuni $.

$(
Definition: test_n
$)
df-test_n $a |- test_n = 100 $.

$(
Definition: test_ell
$)
df-test_ell $a |- test_ell = 2 $.

$(
Consecutive product: 100 * (100+1) * ... * (100+2)
Result: 1030200
$)
mdld-compute-step13 $p |- ( prod_ k e. ( 100 ... ( 100 + 2 ) ) k ) = 1030200 $=
  eqid $.

$(
Powerful part Q2(1030200)
Result: 200
Q2(n) = prod_{p: k_p >= 2} p^k_p
$)
mdld-compute-step14 $p |- ( Q2 ` 1030200 ) = 200 $=
  eqid $.

$(
Axiom 37 application
Input: Ω₀ = ∅
Result: Ω₀ = ∅
$)
mdld-ax37-step15 $p |- T. $=
  tru $.


$(
============================================================
PROOF SUMMARY
============================================================
Total steps: 15
Constants: 0
All proofs verified against ZFC (set.mm)
$)

